### ISSUE TITLE
Better examples in README

### ISSUE THREAD

**Issue by robooo** [jreese/aiomultiprocess#13]
### Description
I used code from the README file

```
from aiohttp import request
from aiomultiprocess import Pool

async def fetch(url):
    return await request("GET", url)

urls = ["https://jreese.sh", ...]
async with Pool() as pool:
    result = await pool.map(fetch, urls)
```

result is 

```
async with Pool() as pool:
         ^
SyntaxError: invalid syntax
```

Then I follow the https://speakerdeck.com/jreese/thinking-outside-the-gil-2?slide=42 and wrapped it to function like 

```
async def fetch_all(urls):
    async with Pool() as pool:
        results = await pool.map(fetch, urls)

urls = ["https://github.com", "https://google.com"]
fetch_all(urls)
```

I've ended with 

```
try3.py:44: RuntimeWarning: coroutine 'fetch_all' was never awaited
  fetch_all(urls)
```
so do I still need to use some asyncio function? 
and I didn't find any example how to read result from _fetch_all_ only make _return results_? 

### Details

* OS: Ubuntu 16.04
* Python version: 3.6.8
* aiomultiprocess version: 0.5.0
* Can you repro on master?
* Can you repro in a clean virtualenv?

**Comment by jreese** [comment]
Anything async needs to be contained within an `async def` function, and you'll need to start an asyncio event loop to run your `fetch_all` async function from a synchronous context.  I would suggest reading through the official asyncio docs to better familiarize yourself with common idioms:  https://docs.python.org/3/library/asyncio.html

That said, I've updated the readme to contain working, self-contained examples.  They use the new `asyncio.run()` helper from Python 3.7, but you should be able to replace that with something like:

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())

Cheers

**Comment by robooo** [comment]
@jreese Thank you!
you have one more bracket at `return await response.text("utf-8"))`
and with python3.6 and using 

```
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

and printing results I'm getting `[TypeError("object ClientResponse can't be used in 'await' expression",), TypeError("object ClientResponse can't be used in 'await' expression",)]` Do you have any idea what I missed? (with python3.7 it works)

**Comment by jreese** [comment]
I fixed the typoes in the readme, but I can't replicate your error on either Python 3.7.2 or 3.6.8.  Running the following code exits successfully: https://gist.github.com/jreese/d554e4e7b6f3c8a6030c2ad1a16f941e
