### ISSUE TITLE
How to execute async generator in Pool

### ISSUE THREAD

**Issue by sagarr** [jreese/aiomultiprocess#15]
### Description
Hi, great library, thanks!

I want to run async generator in Process Pool using aiomultiprocess lib, how can I do that, any pointer. Currently I'm getting error like:
`File "/home/rohankar/anaconda3/lib/python3.6/site-packages/aiomultiprocess/core.py", line 93, in __init__
    raise ValueError(f"target must be coroutine function")
ValueError: target must be coroutine function`

Script that I tried;
```
import asyncio


async def ait(nr):
    for i in range(nr):
        await asyncio.sleep(0.1)
        yield i


from aiomultiprocess import Worker


async def main():
    # This Works
    # async for i in ait(10):
    #     print(i)

    # This throw error
    p = Worker(target=ait, args=(20,))
    p.start()
    print(await p)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())

```

### Details

* OS: Ubuntu 18.04
* Python version: 3.6
* aiomultiprocess version: 0.5.0
* Can you repro on master? didn't try
* Can you repro in a clean virtualenv? didn't try

**Comment by jreese** [comment]
multiprocessing depends on "pickling" objects and return values between the parent and child processes, so any unit of work for the child process must be "pickleable". Generator objects are not currently pickleable in Python, so you can't pass a generator directly.  Also, in this case, you're passing the async generator function itself, which isn't actually a coroutine – it's a normal, synchronous function that immediately returns an async generator object when called.  Your example code is trying to send the async generator function (which itself can't be awaited), but wouldn't use it in any asynchronous way, and doesn't do anything to consume the generator object.

Maybe more specifically, you would want to do something like:

```python
async def ait(nr):
    for i in range(nr):
        await asyncio.sleep(0.1)
        yield i

async def consume(nr):
    async for i in ait(nr):
        print(i)
    return nr

 async def main():
    p = Worker(target=consume, args=(20,))
    p.start()
    print(await p)
