### ISSUE TITLE
How to Passing tow iterable parameters?

### ISSUE THREAD

**Issue by LangziFun** [jreese/aiomultiprocess#18]
### Description

Hi, great library, thanks!

i want to check the url if has image,and my check code is:

	async def get_image(url:'http://test.com/',dirs:'[a.jpg,b.jpg,c.jpg]'):
	    async with aiohttp.ClientSession() as session:
	        for dir in dirs:
	            async with session.get(url=url+dir) as resp:
	                if resp.status == 200:
	                    return await resp.content()
	                    # only need one exists image url
	async def main(url,dirs):
	    async with aiomultiprocess.Pool() as pool:
	        result = await pool.map(get_image,??,??)
	        # hao to set there?
	    print(result)
	
	if __name__ == '__main__':
	    urls = ['http://1.com/','http://2.com/','http://3.com/','http://4.com/',]
	    dirs = ['a.jpg','b.jpg','c.jpg']
	    loop = asyncio.get_event_loop()
	    loop.run_until_complete(main(urls,dirs))

and i want to use pool to mission accomplished，but i don konw hao to desgin.

so,i desgin code again:

	dirs = ['a.jpg', 'b.jpg', 'c.jpg']
	async def get_image(url:'http://test.com/'):
	    async with aiohttp.ClientSession() as session:
	        for dir in dirs:
	            print(url+dir)
	            async with session.get(url=url+dir,timeout=3) as resp:
	                if resp.status == 200:
	                    return await resp.content()
	                    # only need one exists image url
	
	async def main():
	    urls = urls = ['http://1.com/','http://2.com/','http://3.com/','http://4.com/']
	    async with aiomultiprocess.Pool() as pool:
	        result = await pool.map(get_image,urls)
	    print(result)
	
	if __name__ == '__main__':
	    loop = asyncio.get_event_loop()
	    loop.run_until_complete(main())

now is success,but i wang to konw,hao to  passing tow iterable parameters in function main()?

### Details

* OS:windows10
* Python version:3.6
* aiomultiprocess version:0.5.0

**Comment by LangziFun** [comment]
### Description

Hi, great library, thanks!

i want to check the url if has image,and my check code is:

async def get_image(url:'http://test.com/',dirs:'[a.jpg,b.jpg,c.jpg]'):
    async with aiohttp.ClientSession() as session:
        for dir in dirs:
            async with session.get(url=url+dir) as resp:
                if resp.status == 200:
                    return await resp.content()
                    # only need one exists image url
async def main(url,dirs):
    async with aiomultiprocess.Pool() as pool:
        result = await pool.map(get_image,??,??)
        # hao to set there?
    print(result)

if __name__ == '__main__':
    urls = ['http://1.com/','http://2.com/','http://3.com/','http://4.com/',]
    dirs = ['a.jpg','b.jpg','c.jpg']
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(urls,dirs))

and i want to use pool to mission accomplished，but i don konw hao to desgin.

so,i desgin code again:

dirs = ['a.jpg', 'b.jpg', 'c.jpg']
async def get_image(url:'http://test.com/'):
    async with aiohttp.ClientSession() as session:
        for dir in dirs:
            print(url+dir)
            async with session.get(url=url+dir,timeout=3) as resp:
                if resp.status == 200:
                    return await resp.content()
                    # only need one exists image url

async def main():
    urls = urls = ['http://1.com/','http://2.com/','http://3.com/','http://4.com/']
    async with aiomultiprocess.Pool() as pool:
        result = await pool.map(get_image,urls)
    print(result)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())


now is success,but i wang to konw,hao to  passing tow iterable parameters in function main()?

### Details

* OS:windows10
* Python version:3.6
* aiomultiprocess version:0.5.0

**Comment by LangziFun** [comment]
`
### Description

Hi, great library, thanks!

i want to check the url if has image,and my check code is:

async def get_image(url:'http://test.com/',dirs:'[a.jpg,b.jpg,c.jpg]'):
    async with aiohttp.ClientSession() as session:
        for dir in dirs:
            async with session.get(url=url+dir) as resp:
                if resp.status == 200:
                    return await resp.content()
                    # only need one exists image url
async def main(url,dirs):
    async with aiomultiprocess.Pool() as pool:
        result = await pool.map(get_image,??,??)
        # hao to set there?
    print(result)

if __name__ == '__main__':
    urls = ['http://1.com/','http://2.com/','http://3.com/','http://4.com/',]
    dirs = ['a.jpg','b.jpg','c.jpg']
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(urls,dirs))

and i want to use pool to mission accomplished，but i don konw hao to desgin.

so,i desgin code again:

dirs = ['a.jpg', 'b.jpg', 'c.jpg']
async def get_image(url:'http://test.com/'):
    async with aiohttp.ClientSession() as session:
        for dir in dirs:
            print(url+dir)
            async with session.get(url=url+dir,timeout=3) as resp:
                if resp.status == 200:
                    return await resp.content()
                    # only need one exists image url

async def main():
    urls = urls = ['http://1.com/','http://2.com/','http://3.com/','http://4.com/']
    async with aiomultiprocess.Pool() as pool:
        result = await pool.map(get_image,urls)
    print(result)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())


now is success,but i wang to konw,hao to  passing tow iterable parameters in function main()?

### Details

* OS:windows10
* Python version:3.6
* aiomultiprocess version:0.5.0


`

**Comment by LangziFun** [comment]
### Description

Hi, great library, thanks!

i want to check the url if has image,and my check code is:

	async def get_image(url:'http://test.com/',dirs:'[a.jpg,b.jpg,c.jpg]'):
	    async with aiohttp.ClientSession() as session:
	        for dir in dirs:
	            async with session.get(url=url+dir) as resp:
	                if resp.status == 200:
	                    return await resp.content()
	                    # only need one exists image url
	async def main(url,dirs):
	    async with aiomultiprocess.Pool() as pool:
	        result = await pool.map(get_image,??,??)
	        # hao to set there?
	    print(result)
	
	if __name__ == '__main__':
	    urls = ['http://1.com/','http://2.com/','http://3.com/','http://4.com/',]
	    dirs = ['a.jpg','b.jpg','c.jpg']
	    loop = asyncio.get_event_loop()
	    loop.run_until_complete(main(urls,dirs))

and i want to use pool to mission accomplished，but i don konw hao to desgin.

so,i desgin code again:

	dirs = ['a.jpg', 'b.jpg', 'c.jpg']
	async def get_image(url:'http://test.com/'):
	    async with aiohttp.ClientSession() as session:
	        for dir in dirs:
	            print(url+dir)
	            async with session.get(url=url+dir,timeout=3) as resp:
	                if resp.status == 200:
	                    return await resp.content()
	                    # only need one exists image url
	
	async def main():
	    urls = urls = ['http://1.com/','http://2.com/','http://3.com/','http://4.com/']
	    async with aiomultiprocess.Pool() as pool:
	        result = await pool.map(get_image,urls)
	    print(result)
	
	if __name__ == '__main__':
	    loop = asyncio.get_event_loop()
	    loop.run_until_complete(main())


now is success,but i wang to konw,hao to  passing tow iterable parameters in function main()?

### Details

* OS:windows10
* Python version:3.6
* aiomultiprocess version:0.5.0

**Comment by jreese** [comment]
You likely want to use `pool.starmap`, which takes a list of tuples, where each tuple is the set of positional parameters the work function takes.  Eg,

```python
async def get_image(url, dirs):
    ...

async def main():
    urls = [...]
    dirs = [...]
    async with Pool() as pool:
        result = await pool.starmap((url, dirs) for url in urls)
```

**Comment by LangziFun** [comment]
thank you so much! :)
