### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'run'

### ISSUE THREAD

**Issue by Jie-Yuan** [jreese/aiomultiprocess#21]
![image](https://user-images.githubusercontent.com/20265321/57708797-89c6e580-769c-11e9-8611-30a604af6373.png)

**Comment by jreese** [comment]
`asyncio.run` is new in Python 3.7.  When using older versions of Python, you will need to substitute this with something like the following:

```python
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by ofarukcaki** [comment]
I have the same problem on Raspbian 10 (buster). I have tried with Python 3.7 and 3.10 (installed from source) but no luck. The same code works on my Windows 10 machine but not working on Raspbian

**Comment by aweussom** [comment]
> I have the same problem on Raspbian 10 (buster). I have tried with Python 3.7 and 3.10 (installed from source) but no luck. The same code works on my Windows 10 machine but not working on Raspbian

You are likely not calling the correct Python version.
https://raspberrytips.com/change-default-python-version/
