### ISSUE TITLE
how to graciously terminate multiprocessing pool when ctrl + c

### ISSUE THREAD

**Issue by shmilylty** [jreese/aiomultiprocess#24]
### Description
I've tried all the methods mentioned in this [article](https://programmer.group/ctrl-c-in-python-can-t-terminate-multiprocessing-pool-solution.html), but when I press ctrl+c, there's still a lot of exception information. how to graciously terminate multiprocessing pool？

### Details

* OS:Win10
* Python version:CPython 3.7.4
* aiomultiprocess version: 0.5.0
* Can you repro on master? Yes
* Can you repro in a clean virtualenv? Yes

**Comment by jreese** [comment]
Generally speaking, if you want to catch and handle ctrl-c gracefully, you should add a signal handler to your asyncio event loop: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.add_signal_handler

Toy example: https://gist.github.com/jreese/18c6f2730c3268c2777e474e11e95859

This handler should be a standard (non-async) function, and either initiate cleanup/shutdown directly, or schedule a coroutine to be executed on the event loop that does the necessary cleanup/shutdown routine.  In the case of aiomultiprocess, that likely means waiting on remaining jobs, calling `join()` on the worker processes, or adding some mechanism for cancelling inflight jobs if they are long running.  Last resort options include `terminate()` or `kill()` on the pool object to forcefully terminate the child processes, though this will likely incur more stack traces from each worker.

**Comment by shmilylty** [comment]
Thx，But I run example:

Traceback (most recent call last):
  File "D:/OneDrive/temp/test.py", line 65, in <module>
    loop.add_signal_handler(signal.SIGINT, handler)
  File "C:\Program Files\Python37\Lib\asyncio\events.py", line 540, in add_signal_handler
    raise NotImplementedError
NotImplementedError

add_signal_handler is NotImplementedError : (

**Comment by jreese** [comment]
I'm not as familiar with windows, but you may be able to use the normal `signal` module to do something similar: https://stackoverflow.com/a/54886771
