### ISSUE TITLE
Coverage is below 100%

### ISSUE THREAD

**Issue by jreese** [jreese/aiomultiprocess#25]
https://codecov.io/gh/jreese/aiomultiprocess

**Comment by ip4368** [comment]
I think it cannot hit 100% unless the code coverage can detect code runs in child process, it doesn't seem to be the case for now, as the whole run function in PoolWorker is marked untested, but Pool class is definitely used in tests.

**Comment by ip4368** [comment]
Apparently there is a way to do so, adding --concurrency=multiprocessing to the coverage command. I will send PR to enable that along with some more tests.
