### ISSUE TITLE
0.7.0 issue running the examples in the README

### ISSUE THREAD

**Issue by rc-conway** [jreese/aiomultiprocess#39]
Does not occur in 0.6.1
### Description

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

### Details

* OS: macOS Catalina
* Python version: 3.7
* aiomultiprocess version: 0.7.0
* Can you repro on master? haven't tried.  Used PyPi version 
* Can you repro in a clean virtualenv? yes

**Comment by jreese** [comment]
I'm curious how you're running this.  Are you using a special build of Python or something to pre-package dependencies?  My understanding from reading the docs for `multiprocessing.freeze_support()` is that it only applies to Windows (not macOS), and `freeze_support()` should be called at the entry point of the application, not by an imported module. https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support

**Comment by rc-conway** [comment]
I am running this on MacOS in a miniconda environment built using `conda devenv`.
So technically not running in a `virtualenv`.

But again 0.6.1 runs no problem.

Just tried in a clean python 3.7 conda environment with only `aiohttp` and `aiomultiprocess==0.7.0` and same result

**Comment by rc-conway** [comment]
Just tried a clean conda env python 3.8.0 and also did not work.

**Comment by jreese** [comment]
I'm guessing miniconda triggers the frozen process warnings that were officially for use with Windows. This is related to the change from using forked processes to spawned processes, which has also become the default behavior on macOS starting in Python 3.8.

You will need to call `multiprocessing.freeze_support()` before using aiomultiprocess.  If that still doesn't work, then you can use `aiomultiprocess.set_spawn_method("fork")` to revert to the old behavior, though that will be officially unsupported in Python 3.8.

**Comment by rc-conway** [comment]
Thanks for the follow up.

**Comment by austinnichols101** [comment]
Same problem with python 3.7.4 and aiomultiprocess 0.7.0 (works with 0.6.1)

```
import asyncio
from aiohttp import request
from aiomultiprocess import Process

async def put(url, params):
    async with request("PUT", url, params=params) as response:
        pass

async def main():
    p = Process(target=put, args=("https://jreese.sh", {}))
    await p

asyncio.run(main())
```

**Comment by jreese** [comment]
I think I better understand the cause of this, now. The problem here is that the spawned child processes will spin up a fresh CPython interpreter, which will then attempt to reimport the modules containing the functions to be executed.  If that bit of code initiating the execution (the `asyncio.run(main())` part) is not gated by the standard `if __name__ == "__main__":` condition, then the spawned process is unintentionally attempting to create more process pools again, in each child process, ad infinitum.

Instead, you should be attempting to use something like:

```python
import asyncio
from aiohttp import request
from aiomultiprocess import Process

async def put(url, params):
    async with request("PUT", url, params=params) as response:
        pass

async def main():
    p = Process(target=put, args=("https://jreese.sh", {}))
    await p

if __name__ == "__main__":
    asyncio.run(main())
```

I will update the examples in the readme to follow this pattern.

**Comment by rc-conway** [comment]
I ran the code gated by:
```python
if __name__ == "__main__":
    asyncio.run(main())
```
And I still encountered the ` freeze_support()` error

Using:
```python
if __name__ == '__main__':
    import aiomultiprocess
    aiomultiprocess.set_start_method("fork")
    asyncio.run(main())
```
provided a successful run
