### ISSUE TITLE
ValueError: cannot find context for 'fork' 

### ISSUE THREAD

**Issue by motika233** [jreese/aiomultiprocess#6]
### Description
When importing aiomultiprocess, I got this error. 

### Details
from aiomultiprocess import Pool

Traceback (most recent call last):

  File "<ipython-input-39-066f50ec84fc>", line 1, in <module>
    from aiomultiprocess import Pool

  File "C:\Users\patlo\Anaconda3\lib\site-packages\aiomultiprocess\__init__.py", line 11, in <module>
    from .core import Pool, Process, Worker

  File "C:\Users\patlo\Anaconda3\lib\site-packages\aiomultiprocess\core.py", line 35, in <module>
    context = multiprocessing.get_context("fork")

  File "C:\Users\patlo\Anaconda3\lib\multiprocessing\context.py", line 238, in get_context
    return super().get_context(method)

  File "C:\Users\patlo\Anaconda3\lib\multiprocessing\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method)

ValueError: cannot find context for 'fork'

* OS:
* Python version:3.6.3
* aiomultiprocess version:0.4.0
* Can you repro on master? Yes
* Can you repro in a clean virtualenv? NO

**Comment by jreese** [comment]
Apparently python doesn't support any multiprocessing contexts except "spawn" on Windows.  It probably makes sense to just use the default context rather than specifying one in specific.

**Comment by kevinpound121** [comment]
> Apparently python doesn't support any multiprocessing contexts except "spawn" on Windows. It probably makes sense to just use the default context rather than specifying one in specific.

Sir,  is there any solution or suggestion for this error in Windows now?

**Comment by jreese** [comment]
Sorry for the delay on this.  Windows should be correctly supported (but mostly untested by me) on the master branch now (and tag v0.5.0), and will be available on PyPI soon.  If there are further problems with Windows on v0.5.0, please open new issues.
