### ISSUE TITLE
whats the magic of hard coding 0.005 at `await asyncio.sleep()`

### ISSUE THREAD

**Issue by openalmeida** [jreese/aiomultiprocess#9]
### Description

sorry for this boring question,
but any reasons it is have to be 0.005 ?

maybe a constant of module or package level as an instead.
especially the `loop()` of `Pool` about `# let someone else do some work for once`
https://github.com/jreese/aiomultiprocess/blob/ef791e96af4d8fd802fecb20353f5abdc002ee0a/aiomultiprocess/core.py#L292

~P.S it seems the class `Process` missing a member function `terminate`~

~P.S.S maybe https://github.com/jreese/aiomultiprocess/issues/5 refers to [python fork() support stuff of asyncio](https://bugs.python.org/issue21998)~ seems python 3.6.1+ works, check my last reply of #5

### Details

* OS:
* Python version:
* aiomultiprocess version:
* Can you repro on master?
* Can you repro in a clean virtualenv?

**Comment by jreese** [comment]
Nothing too special about that timing, beyond some basic timing/perf tests that showed it performing well with my workloads.  I'd be happy to review a PR making it easier to modify or specify these timings in calling code at runtime.
